blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name


urlpatterns = [
    path('blog/', BlogListView.as_view(), name='blog_list'),
    path('blog/create', BlogCreateView.as_view(), name='blog_create'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', 'mailing')),
    path('users/', include('users.urls', 'users')),
    path('', include('blog.urls', 'blog')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}

class Blog(models.Model):
    title = models.CharField(max_length=255, verbose_name="Заголовок статьи", help_text='Введите заголовок статьи')
    body = models.TextField(verbose_name='Содержимое стати', help_text='Добавьте содержимое статьи')
    image = models.ImageField(upload_to='blog/photo/', verbose_name='Превью', help_text='Загрузите превью статьи', **NULLABLE)
    slug = models.SlugField(unique=True, verbose_name='slug', help_text='slug', **NULLABLE)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания', help_text='Укажите дату создания')
    is_published = models.BooleanField(default=True, verbose_name='Признак публикации', help_text='Укажите признак публикации')
    number_views = models.PositiveIntegerField(default=0, verbose_name='Количество просмотров', help_text='Укажите количество просмотров')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

blog/forms.py
from django.forms import ModelForm

from blog.models import Blog
from mailing.forms import StyleFormMixin


class BlogForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'body', 'image', 'slug', 'is_published', 'number_views']

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from pytils.translit import slugify

from blog.forms import BlogForm
from blog.models import Blog
from blog.services import get_cached_blog_list


class BlogListView(ListView):
    model = Blog

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['blog_list'] = get_cached_blog_list()
        return context

class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.number_views += 1
        self.object.save()
        return self.object

class BlogCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Blog
    form_class = BlogForm
    permission_required = "blog.add_blog"
    success_url = reverse_lazy("blog:blog_list")
    login_url = "users:login"
    redirect_field_name = "login"

    def form_valid(self, form):
        new_article = form.save()
        new_article.slug = slugify(new_article.title)
        new_article.save()

        get_cached_blog_list(recached=True)
        return super().form_valid(form)


    def get_success_url(self):
        return reverse('blog:blog_list')



class BlogUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Blog
    form_class = BlogForm
    permission_required = "blog.change_article"
    login_url = "users:login"
    redirect_field_name = "login"

    def form_valid(self, form):
        if form.is_valid():
            new_article = form.save()
            new_article.slug = slugify(new_article.title)
            new_article.save()

            get_cached_blog_list(recached=True)
            return super().form_valid(form)
    def get_success_url(self):
        return reverse('blog:blog_detail', args=[self.kwargs.get('pk')])


class BlogDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy("blog:blog_list")
    permission_required = "blog.delete_article"
    login_url = "users:login"
    redirect_field_name = "login"

    def form_valid(self, form):
        get_cached_blog_list(recached=True)
        return super().form_valid(form)

blog/templates/blog/blog_confirm_delete.html
{% extends 'mailing/base.html'%}
{% block content %}


<div class="row text-start">

    <div class="col-lg-12 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Удаление статьи</h4>
            </div>

            <div class="card-body">
                <div class="card-text">Вы действительно хотите статью {{object.title}} ?</div>
                <form method="post" action="" class="form-floating" enctype="multipart/form-data">
                    <div class="mb-3">

                    {% csrf_token %}




                    </div>


                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                        Удалить
                    </button>

                    <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'blog:blog_list' %}">Отмена</a>

                </form>
            </div>
        </div>
    </div>
</div>



{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'mailing/base.html'%}
{% load static %}
{% load my_tags %}
{% block content %}

<div class="row text-right">
    <div class="col-6">
        <div class="card mb-3 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Изображение</h4>
            </div>
            <div class="card-body">
                <img src="{{object.image|media_filter}}" class="card-img-top" alt={{object.image|media_filter}}>

            </div>
        </div>

    </div>


    <div class="col-6">

        <div class="card mb-3 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{object.title}}</h4>
            </div>


            <div class="card-body">
                <h5 class="card-title">
                    <div style="color: orange"><b>{{object.title}}</b></div>
                </h5>
                <p class="card-text">


                    <br>
                    <b>Наименование: </b>{{object.title}}
                    <br> <br>

                    <b>Создано: </b>{{object.created_at}}
                    <br> <br>
                    <b>Опубликовано: </b>{% if object.is_published %}
                    Да
                    {% else %}
                    Нет
                    {% endif %}
                    <br><br>
                    <small class="text-body-secondary">

                        Просмотры: {{object.number_views}} <br>
                        Slug: {{object.slug}}


                    </small>


                </p>
                <div class="btn-group">

                    <a class="btn btn-outline-info" href="/" role="button">Вернуться на главную страницу сайта</a>

                    <a class="btn btn-outline-info" href="{% url 'blog:blog_list' %}" role="button"> Вернуться на
                        главную
                        страницу блога</a>
                </div>


            </div>
        </div>


    </div>


</div>

<div class="row text-right">
    <div class="col-12">
        <div class="card mb-3 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Текст статьи</h4>
            </div>
            <div class="card-body">
                {{object.body|comment_markdown}}

            </div>
        </div>

    </div>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'mailing/base.html'%}
{% block content %}

<form class="row" method="post" enctype="multipart/form-data">

    <div class="col-12">
        <div class="col-lg-12 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Добавить email</h4>
                </div>
                <div class="card-body">
                    <div class="mb-3">
                        {% csrf_token %}
                        {{form.as_p}}
                    </div>

                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                        {% if object %}
                        Изменить
                        {% else %}
                        Создать
                        {% endif %}


                    </button>
                    <a class="btn btn-lg btn-block btn-outline-info" href="{% url 'blog:blog_list' %}">Назад</a>

                </div>
            </div>
        </div>
    </div>
</form>
</div>


{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'mailing/base.html'%}
{% load static %}
{% load my_tags %}
{% block content %}


<div class="row text-right">
    {% if perms.blog.add_blog %}
    <div class="col-12 mb-3">
        <div class="card mb-3 box-shadow">
            <br>
            <div class="btn-group">
                &nbsp; &nbsp; &nbsp; <a class="p-2 btn btn-outline-primary btn-lg btn-block"
                                        href="{%url 'blog:blog_create' %}">Добавить статью в блог</a> &nbsp; &nbsp;

                &nbsp;
            </div>
            <br>
        </div>
    </div>
    {%endif%}

    {% for object in object_list %}

    <div class="col-4">

        <div class="card mb-3 box-shadow">
            <img src="{{ object.image | media_filter }}" class="card-img-top" alt={{object.image|media_filter}}>


            <div class="card-body">
                <h5 class="card-title">
                    <div style="color: orange"><b> {{object.title}}</b></div>
                </h5>
                <p class="card-text">
                  {% if object.body|comment_markdown|length >= 300 %}
                    {{ object.body|comment_markdown|slice:":300"}} ...
                    {% else %}
                    {{ object.body}}
                    {% endif %}
                </p>
                <br>
                <p class="card-text">
                    <b>Опубликовано: </b> {{object.created_at}}<br>
                   </p>


                <div class="btn-group">
                    {% comment "кнопка спрятана, теперь переход по slug %}
                     <a class="btn btn-outline-success" href="{% url 'blog:blog_detail' object.pk%}" role="button">Посмотреть</a>

                     <a class="btn btn-outline-success" href="{% url 'blog:blog_update' object.pk%}" role="button">Изменить</a>

                    <a class="btn btn-outline-success" href="{% url 'blog:blog_delete' object.pk%}" role="button">Удалить</a>
                    {% endcomment %}

                    <a class="btn btn-outline-success" href="{% url 'blog:blog_detail' object.pk%}" role="button">Посмотреть</a>

                    {% if perms.blog.change_blog or user.is_superuser %}
                    <a class="btn btn-outline-success" href="{% url 'blog:blog_update' object.pk%}" role="button">Изменить</a>
                    {%endif%}

                   {% if perms.blog.delete_blog or user.is_superuser %}

                     <a class="btn btn-outline-danger" href="{% url 'blog:blog_delete' object.pk%}" role="button">Удалить</a>

                    {%endif%}







                </div>

            </div>

    </div>


    </div>
    {% endfor %}



</div>

{% endblock %}